apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfomock
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /isalive
    initialDelay: 10
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /isready
    initialDelay: 10
    timeout: 1
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  ingresses:
    - "https://syfomock.nais.oera-q.local"
    - "https://syfomock.dev-sbs.nais.io"
