export const Diagnoser = {
    A01: "Smerte generell/flere steder",
    A02: "Frysninger",
    A03: "Feber",
    A04: "Slapphet/tretthet",
    A05: "Sykdomsfølelse",
    A06: "Besvimelse/synkope",
    A07: "Bevisstløshet/koma",
    A08: "Hevelse/oppfylning IKA",
    A09: "Svetteproblemer",
    A10: "Blødning IKA",
    A11: "Brystsmerte IKA",
    A13: "Engstelig for behandling",
    A16: "Irritabelt/urolig spedbarn",
    A18: "Bekymret/opptatt av utseende IKA",
    A20: "Dødshjelp diskusjon/spørsmål om",
    A21: "Økt risiko for ondartet svulst",
    A23: "Risiko for sykdom IKA",
    A25: "Engstelig for døden",
    A26: "Engstelig for kreft IKA",
    A27: "Engstelig for sykdom IKA",
    A28: "Redusert funksjonsevne IKA",
    A29: "Generelle symptomer/plager IKA",
    A70: "Tuberkulose",
    A71: "Meslinger",
    A72: "Vannkopper",
    A73: "Malaria",
    A74: "Røde hunder",
    A75: "Mononukleose",
    A76: "Virussykdom med utslett IKA",
    A77: "Virussykdom IKA",
    A78: "Infeksjonssykdom IKA",
    A79: "Ondartet svulst IKA",
    A80: "Skade/traume IKA",
    A81: "Multiple skader/traumer",
    A82: "Følgetilstand skade/traume",
    A84: "Legemiddelforgiftning",
    A85: "Bivirkning legemiddel",
    A86: "Toksisk virkning stoff IKA",
    A87: "Komplikasjon etter behandling",
    A88: "Skadevirkning av fysisk faktor",
    A89: "Komplikasjoner/problemer med protese",
    A90: "Medfødt feil IKA/multiple feil",
    A91: "Unormalt funn ved undersøkelse IKA",
    A92: "Allergi/allergisk reaksjon IKA",
    A93: "Prematurt/immaturt levendefødt barn",
    A94: "Perinatal sykelighet IKA",
    A95: "Perinatal død",
    A96: "Død/dødsfall IKA",
    A97: "Administrativ kontakt/undersøkelse",
    A98: "Individforebyggende tiltak",
    A981: "Cytologi livmorhals screening",
    A99: "Helseproblem/sykdom IKA",
    B02: "Lymfeknuter forstørrede/smertefulle",
    B04: "Blod/blodsystemet symptomer/plager",
    B25: "Engstelig for HIV/AIDS",
    B26: "Engstelig for kreft blod/lymfesystem",
    B27: "Engstelig for blod/lymfe sykdom IKA",
    B28: "Redus funksjonsevne pga blod/lymfe",
    B29: "Blod/lymfesystem sympt/plager IKA",
    B70: "Lymfadenitt akutt",
    B71: "Lymfadenitt kronisk/uspesifikk",
    B72: "Hodgkins sykdom/lymfom",
    B73: "Leukemi",
    B74: "Ondartet svulst blod/lymfesystem IKA",
    B75: "Godartet/uspes svulst blod/lymfe",
    B76: "Miltruptur traumatisk",
    B77: "Skade blod/lymfesystem IKA",
    B78: "Arvelig hemolytisk anemi",
    B79: "Medfødt feil blod/lymfesystem IKA",
    B80: "Jernmangelanemi",
    B81: "Anemi B12/folsyremangel",
    B82: "Anemi IKA",
    B83: "Purpura/koagulasjonsdefekt",
    B84: "Unormale hvite blodceller",
    B87: "Forstørret milt",
    B90: "HIV-sykdom/AIDS",
    B99: "Blod/lymfe/milt sykdom IKA",
    D01: "Abdominalsmerte/krampe generell",
    D02: "Abdominalsmerte epigastriet",
    D03: "Halsbrann",
    D04: "Endetarmssmerte",
    D05: "Perianal kløe",
    D06: "Abdominalsmerte lokalisert IKA",
    D07: "Dyspepsi/fordøyelsesbesvær",
    D08: "Flatulens/oppblåsthet/raping",
    D09: "Kvalme",
    D10: "Oppkast/brekninger",
    D11: "Diaré",
    D12: "Forstoppelse",
    D13: "Gulsott",
    D14: "Oppkast med blod/hematemese",
    D15: "Melena",
    D16: "Rektalblødning",
    D17: "Inkontinens avføring",
    D18: "Endring i avføring/avføringsvane",
    D19: "Tenner/tannkjøtt symptomer/plager",
    D20: "Munn/tunge/lepper symptomer/plager",
    D21: "Svelgebesvær",
    D23: "Forstørret lever",
    D24: "Abdominal oppfylling/kul IKA",
    D25: "Utspilt abdomen",
    D26: "Engstelig for kreft fordøyelsesyst",
    D27: "Engstelig for fordøyelsesykdom IKA",
    D28: "Redusert funksjonsevne fordøy probl",
    D29: "Fordøyelsesyst symptomer/plager IKA",
    D70: "Tarminfeksjon",
    D71: "Kusma",
    D72: "Virushepatitt",
    D73: "Gastroenteritt antatt infeksiøs",
    D74: "Ondartet svulst magesekk",
    D75: "Ondartet svulst tykktarm/endetarm",
    D76: "Ondartet svulst bukspyttkjertel",
    D77: "Ondartet svulst fordøyelsesyst IKA",
    D78: "Godartet/uspes svulst fordøyelsessys",
    D79: "Fremmedlegeme fordøyelsessystemet",
    D80: "Skade fordøyelsesystemet IKA",
    D81: "Medfødt feil fordøyelsesystem",
    D82: "Tenner/tannkjøtt sykdom",
    D83: "Munn/tunge/lepper sykdom",
    D84: "Spiserørssykdom",
    D85: "Sår i tolvfingertarm",
    D86: "Magesår IKA",
    D87: "Funksjonelle plager magesekk",
    D88: "Appendisitt",
    D89: "Lyskebrokk",
    D90: "Mellomgulvsbrokk",
    D91: "Abdominalt brokk IKA",
    D92: "Divertikkelsykdom i tarm",
    D93: "Irritabel tarm-syndrom",
    D94: "Kronisk enteritt/ulcerøs kolitt",
    D95: "Analfissur/perianal abscess",
    D96: "Orme-/parasittsykdom",
    D97: "Leversykdom IKA",
    D98: "Galleveisbetennelse/gallesten",
    D99: "Sykdom i fordøyelsessystemet IKA",
    F01: "Øyesmerte",
    F02: "Rødt øye",
    F03: "Tåreflod/sekresjon øye",
    F04: "Synlige flekker/tråder i synsfelt",
    F05: "Synsforstyrrelse IKA",
    F13: "Øye unormal følelse",
    F14: "Øye unormal bevegelse",
    F15: "Øye unormalt utseende",
    F16: "Øyelokk symptomer/plager",
    F17: "Briller symptomer/plager",
    F18: "Kontaktlinser symptomer/plager",
    F27: "Engstelig for øyesykdom",
    F28: "Redusert funksjonsevne pga øyeprobl",
    F29: "Øye symptomer/plager IKA",
    F70: "Infeksiøs konjunktivitt",
    F71: "Allergisk konjunktivitt",
    F72: "Øyelokkbetennelse",
    F73: "Øye infeksjon/betennelse IKA",
    F74: "Svulst i øye/øyehule",
    F75: "Kontusjon/blødning i øye",
    F76: "Fremmedlegeme øye",
    F79: "Skade øye IKA",
    F80: "Tåreveisstenose/atresi spedbarn",
    F81: "Medfødt feil øye IKA",
    F82: "Netthinneløsning/rift",
    F83: "Retinopati",
    F84: "Makuladegenerasjon",
    F85: "Hornhinnesår",
    F86: "Trakom",
    F91: "Brytningsforstyrrelse",
    F92: "Grå stær/katarakt",
    F93: "Glaukom",
    F94: "Blindhet",
    F95: "Skjeling/strabisme",
    F99: "Øyesykdom IKA",
    H01: "Øresmerte/øreverk",
    H02: "Hørsel symptomer/plager",
    H03: "Øresus",
    H04: "Øreflod/sekresjon",
    H05: "Blødning øre",
    H13: "Øreplugg/øretetthet",
    H15: "Bekymret/opptatt av ørenes utseende",
    H27: "Engstelig for øresykdom",
    H28: "Redusert funksjonsevne pga øreprobl",
    H29: "Øre symptomer/plager IKA",
    H70: "Ytre øre betennelse",
    H71: "Mellomørebetennelse akutt",
    H72: "Mellomørebetennelse serøs",
    H73: "Tuba auditiva betennelse",
    H74: "Mellomørebetennelse kronisk",
    H75: "Svulst øre",
    H76: "Fremmedlegeme øre",
    H77: "Perforert trommehinne IKA",
    H78: "Overflateskade ytre øre",
    H79: "Skade øre IKA",
    H80: "Medfødt feil øre",
    H81: "Ørevoks",
    H82: "Svimmelhetssyndrom",
    H83: "Otosklerose",
    H84: "Hørselstap aldersbetinget",
    H85: "Hørselstap støyskade",
    H86: "Døvhet/hørselstap IKA",
    H99: "Øresykdom IKA",
    K01: "Smerte relatert til hjertet",
    K02: "Trykk/sammensnøring hjertet",
    K03: "Smerte relatert til kretsløpet IKA",
    K04: "Hjertebank",
    K05: "Uregelmessige hjerteslag IKA",
    K06: "Utvidede vener",
    K07: "Hovne ankler/ødem",
    K22: "Økt risiko for hjerte-karsykdom",
    K24: "Engstelig for hjertesykdom",
    K25: "Engstelig for høyt blodtrykk",
    K27: "Engstelig for hjerte-karsykdom IKA",
    K28: "Redus funksjonsevne hjerte-karprobl",
    K29: "Hjerte-karsyst symptomer/plager IKA",
    K70: "Infeksjon hjerte-karsystemet",
    K71: "Reumatisk feber/hjertesykdom",
    K72: "Svulst i hjerte",
    K73: "Medfødt feil hjerte-karsystemet",
    K74: "Iskemisk hjertesykdom med angina",
    K75: "Akutt hjerteinfarkt",
    K76: "Iskemisk hjertesykdom kronisk IKA",
    K77: "Hjertesvikt",
    K78: "Atrieflimmer/flutter",
    K79: "Paroksysmal takykardi",
    K80: "Hjertearytmi IKA",
    K81: "Bilyd hjerte/arterier IKA",
    K82: "Pulmonal hjertesykdom",
    K83: "Hjerteklaffesykdom IKA",
    K84: "Hjertesykdom IKA",
    K85: "Forhøyet blodtrykk IKA",
    K86: "Hypertensjon ukomplisert",
    K87: "Hypertensjon med komplikasjoner",
    K88: "Postural hypotensjon",
    K89: "Forbigående cerebral iskemi",
    K90: "Hjerneslag",
    K91: "Cerebrovaskulær sykdom",
    K92: "Aterosklerose/perifer karsykdom",
    K93: "Lungeemboli",
    K94: "Årebetennelse",
    K95: "Åreknuter underekstremitet",
    K96: "Hemoroider",
    K99: "Hjerte-karsykdom IKA",
    L01: "Nakke symptomer/plager",
    L02: "Rygg symptomer/plager",
    L03: "Korsrygg symptomer/plager",
    L04: "Brystkasse symptomer/plager",
    L05: "Flanke/armhule symptomer/plager",
    L07: "Kjeve symptomer/plager",
    L08: "Skulder symptomer/plager",
    L09: "Arm symptomer/plager",
    L10: "Albue symptomer/plager",
    L11: "Håndledd symptomer/plager",
    L12: "Hånd/finger symptomer/plager",
    L13: "Hofte symptomer/plager",
    L14: "Legg/lår symptomer/plager",
    L15: "Kne symptomer/plager",
    L16: "Ankel symptomer/plager",
    L17: "Fot/tå symptomer/plager",
    L18: "Utbredte muskelsmerter/fibromyalgi",
    L19: "Muskel symptomer/plager IKA",
    L20: "Ledd symptomer/plager IKA",
    L26: "Engstelig for kreft muskel-skj-syst",
    L27: "Engstelig for sykd musk-skj-syst IKA",
    L28: "Redus funksjonsevne musk-skj-probl",
    L29: "Muskel-skj-syst sympt/plager IKA",
    L70: "Infeksjon muskel-skjelettsystemet",
    L71: "Ondartet svulst muskel-skj-syst",
    L72: "Brudd underarm",
    L73: "Brudd legg/ankel",
    L74: "Brudd hånd/fot",
    L75: "Brudd lårben/lårhals",
    L76: "Brudd IKA",
    L77: "Forstuving/forstrekking ankel",
    L78: "Forstuving/forstrekking kne",
    L79: "Forstuving/forstrekking ledd IKA",
    L80: "Dislokasjon/subluksasjon",
    L81: "Skade muskel-skj-syst IKA",
    L82: "Medfødt feil muskel-skj-syst",
    L83: "Nakkesyndrom",
    L84: "Ryggsyndrom uten smerteutstråling",
    L85: "Ervervet deformitet ryggsøyle",
    L86: "Ryggsyndrom med smerteutstråling",
    L87: "Bursitt/tendinitt/synovitt IKA",
    L88: "Reumatoid artritt/reumatisk sykdom",
    L89: "Hofteleddsartrose",
    L90: "Kneleddsartrose",
    L91: "Artrose IKA",
    L92: "Skuldersyndrom",
    L93: "Tennisalbue/lateral epikondylitt",
    L94: "Osteokondrose",
    L95: "Osteoporose",
    L96: "Akutt indre kneskade",
    L97: "Godartet/uspes svulst musk-skj-syst",
    L98: "Ervervet deformitet ekstremitet",
    L99: "Muskel-skjelettsykdom IKA",
    N01: "Hodepine",
    N03: "Ansiktssmerte",
    N04: "Restless legs",
    N05: "Prikking/parestesi i hender/føtter",
    N06: "Forstyrrelser i hudens følsomhet IKA",
    N07: "Krampeanfall/kramper",
    N08: "Unormale/ufrivillige bevegelser",
    N16: "Forstyrrelse i lukt/smak",
    N17: "Svimmelhet IKA",
    N18: "Lammelse/svakhet",
    N19: "Talevansker",
    N26: "Engstelig for kreft nervesystemet",
    N27: "Engstelig for sykdom nervesyst IKA",
    N28: "Redus funksjonsevne probl nervesyst",
    N29: "Nervesystem symptomer/plager IKA",
    N70: "Poliomyelitt",
    N71: "Meningitt/encefalitt",
    N72: "Stivkrampe",
    N73: "Infeksjon sentralnervesyst IKA",
    N74: "Ondartet svulst nervesystemet",
    N75: "Godartet svulst nervesystemet",
    N76: "Uspesifisert svulst nervesystemet",
    N79: "Hjernerystelse",
    N80: "Hodeskade IKA",
    N81: "Skade nervesystemet IKA",
    N85: "Medfødt feil nervesystemet",
    N86: "Multippel sklerose",
    N87: "Parkinsonisme",
    N88: "Epilepsi",
    N89: "Migrene",
    N90: "Cluster-hodepine",
    N91: "Facialisparese",
    N92: "Trigeminusnevralgi",
    N93: "Carpal tunnel syndrom",
    N94: "Perifer nevropati",
    N95: "Tensjonshodepine",
    N99: "Sykdom i nervesystemet IKA",
    P01: "Følelse angst/nervøs/anspent",
    P02: "Psykisk ubalanse situasjonsbetinget",
    P03: "Depresjonsfølelse",
    P04: "Irritabel atferd/følelse",
    P05: "Senilitet, atferd/følelse gammel",
    P06: "Søvnforstyrrelse",
    P07: "Seksuell drift/lyst hemmet",
    P08: "Seksuell tilfredsstillelse hemmet",
    P09: "Seksuell legning bekymret for",
    P10: "Stamming/tics",
    P11: "Spiseforstyrrelse hos barn",
    P12: "Sengevæting/enuresis IKA",
    P13: "Enkoprese",
    P15: "Kronisk alkoholmisbruk",
    P16: "Akutt alkoholmisbruk",
    P17: "Tobakkmisbruk",
    P18: "Legemiddelmisbruk",
    P19: "Stoffmisbruk",
    P20: "Hukommelsesforstyrrelse",
    P22: "Atferdsforstyrrelse barn",
    P23: "Atferdsforstyrrelse ungdom",
    P24: "Spesifikke utviklingsforstyrrelser",
    P25: "Livsfaseproblem voksen",
    P27: "Engstelig for psykisk sykdom",
    P28: "Redusert funksjonsevne psyk problem",
    P29: "Psykiske symptomer/plager IKA",
    P70: "Demens",
    P71: "Organisk psykisk lidelse IKA",
    P72: "Schizofreni",
    P73: "Affektiv lidelse",
    P74: "Angstlidelse",
    P75: "Dissosiativ/somatoform lidelse",
    P76: "Depressiv lidelse",
    P77: "Selvmord/selvmordsforsøk",
    P78: "Nevrasteni",
    P79: "Fobi/obsessiv-kompulsiv lidelse",
    P80: "Personlighetsforstyrrelse",
    P81: "Hyperkinetisk forstyrrelse",
    P82: "Posttraumatisk stresslidelse",
    P85: "Psykisk utviklingshemning",
    P86: "Anorexia nervosa/bulimi",
    P98: "Psykose IKA",
    P99: "Psykisk lidelse IKA",
    R01: "Smerte luftveier",
    R02: "Kortpustethet/dyspné",
    R03: "Piping i brystet",
    R04: "Pusteproblem IKA",
    R05: "Hoste",
    R06: "Neseblødning",
    R07: "Nysing/tetthet i nese",
    R08: "Nese symptomer/plager IKA",
    R09: "Bihule symptomer/plager IKA",
    R21: "Hals symptomer/plager",
    R23: "Stemme symptomer/plager",
    R24: "Blodig oppspytt/hemoptyse",
    R25: "Unormalt oppspytt/ekspektorat",
    R26: "Engstelig for kreft luftveier",
    R27: "Engstelig for sykdom luftveier IKA",
    R28: "Redusert funksjonsevne luftveisprobl",
    R29: "Luftveier symptomer/plager IKA",
    R71: "Kikhoste",
    R72: "Streptokokkhals",
    R73: "Nesebyll",
    R74: "Akutt øvre luftveisinfeksjon",
    R75: "Bihulebetennelse",
    R76: "Akutt tonsillitt",
    R77: "Akutt laryngitt/trakeitt",
    R78: "Akutt bronkitt/bronkiolitt",
    R79: "Kronisk bronkitt",
    R80: "Influensa",
    R81: "Lungebetennelse",
    R82: "Pleuritt IKA",
    R83: "Luftveisinfeksjon IKA",
    R84: "Ondartet svulst bronkie/lunge",
    R85: "Ondartet svulst luftveier IKA",
    R86: "Godartet svulst luftveier",
    R87: "Fremmedlegeme i nese/larynks/bronkie",
    R88: "Skade luftveier IKA",
    R89: "Medfødt feil luftveier",
    R90: "Hypertrofi tonsiller/adenoid vev",
    R92: "Uspesifisert svulst luftveier",
    R95: "Kronisk obstruktiv lungesykdom",
    R96: "Astma",
    R97: "Allergisk rinitt",
    R98: "Hyperventileringssyndrom",
    R99: "Luftveissykdom IKA",
    S01: "Smerte/ømhet hud",
    S02: "Hudkløe",
    S03: "Vorter",
    S04: "Lokalisert hevelse/kul hud",
    S05: "Utbredte hevelser/kuler hud",
    S06: "Lokalisert utslett hud",
    S07: "Utbredt utslett hud",
    S08: "Forandring av hudfarge IKA",
    S09: "Infeksjon finger/tå",
    S10: "Abscess/furunkel",
    S11: "Hudinfeksjon posttraumatisk",
    S12: "Insektstikk/bitt",
    S13: "Bitt av dyr/menneske",
    S14: "Forbrenning/skålding",
    S15: "Fremmedlegeme hud",
    S16: "Kontusjon/slag hud",
    S17: "Skrubbsår/blemmer",
    S18: "Åpent sår/kutt",
    S19: "Skade hud/underhud IKA",
    S20: "Liktorn/fortykket underhud",
    S21: "Hudstruktur symptomer/plager",
    S22: "Negl symptomer/plager",
    S23: "Håravfall/skallethet",
    S24: "Hår/hodebunn symptomer/plager IKA",
    S26: "Engstelig for kreft hud",
    S27: "Engstelig for hudsykdom IKA",
    S28: "Redusert funksjonsevne pga hudprobl",
    S29: "Hud symptomer/plager IKA",
    S70: "Herpes zoster",
    S71: "Herpes simplex IKA",
    S72: "Infestasjon midd",
    S73: "Infestasjon parasitt IKA",
    S74: "Ringorm/hudsopp IKA",
    S75: "Candidainfeksjon hud",
    S76: "Hudinfeksjon IKA",
    S77: "Ondartet svulst hud",
    S78: "Lipom",
    S79: "Godartet/uspesifisert svulst hud IKA",
    S80: "Solutløst keratose/solforbrenning",
    S81: "Hemangiom/lymfangiom",
    S82: "Pigmentnevus",
    S83: "Medfødt feil hud/underhud IKA",
    S84: "Brennkopper",
    S85: "Pilonidalcyste/-fistel",
    S86: "Seboréisk dermatitt",
    S87: "Atopisk dermatitt/eksem",
    S88: "Kontakt-/allergisk dermatitt IKA",
    S89: "Bleiedermatitt",
    S90: "Pityriasis rosea",
    S91: "Psoriasis",
    S92: "Svettekjertelsykdom",
    S93: "Talgcyste",
    S94: "Inngrodd negl",
    S95: "Molluscum contagiosum",
    S96: "Akne",
    S97: "Kronisk hudsår",
    S98: "Urticaria",
    S99: "Hud/underhud sykdom IKA",
    T01: "Økt tørste",
    T02: "Økt matlyst",
    T03: "Nedsatt matlyst",
    T04: "Ernæringsproblem barn",
    T05: "Ernæringsproblem voksen",
    T07: "Vektøkning",
    T08: "Vekttap",
    T10: "Forsinket vekst",
    T11: "Uttørring",
    T26: "Engstelig for kreft endokrine system",
    T27: "Engstelig endokr/metabol/ernær sykd",
    T28: "Red funk evne endo/metab/ernær probl",
    T29: "Endok/metab/ernær sympt/plager IKA",
    T70: "Infeksjon endokrine system",
    T71: "Ondartet svulst tyreoidea",
    T72: "Godartet svulst tyreoidea",
    T73: "Svulst endokrine organ IKA",
    T78: "Ductus/cystis tyreoglossus",
    T80: "Medfødt feil endokr/metabol syst IKA",
    T81: "Struma",
    T82: "Fedme",
    T83: "Overvekt",
    T85: "Hypertyreose/tyreotoksikose",
    T86: "Hypotyreose/myksødem",
    T87: "Hypoglykemi",
    T89: "Diabetes type 1",
    T90: "Diabetes type 2",
    T91: "Vitaminmangel/ernæringsforstyrrelse",
    T92: "Urinsyregikt",
    T93: "Lipidstoffskifte forstyrrelse",
    T99: "Endokrin/metabol/ernær sykd IKA",
    U01: "Smerte vannlating",
    U02: "Hyppig vannlating",
    U04: "Urininkontinens",
    U05: "Vannlatingsproblemer IKA",
    U06: "Hematuri",
    U07: "Urin symptomer/plager IKA",
    U08: "Urinretensjon",
    U13: "Blære symptomer/plager IKA",
    U14: "Nyre symptomer/plager",
    U26: "Engstelig for kreft urinveier",
    U27: "Engstelig for sykdom urinveier IKA",
    U28: "Redusert funksjonsevne urinveisprobl",
    U29: "Urinveier symptomer/plager IKA",
    U70: "Nyrebekkenbetennelse",
    U71: "Cystitt/urinveisinfeksjon IKA",
    U72: "Uretritt",
    U75: "Ondartet svulst nyre",
    U76: "Ondartet svulst urinblære",
    U77: "Ondartet svulst urinveier IKA",
    U78: "Godartet svulst urinveier",
    U79: "Uspesifisert svulst urinveier",
    U80: "Skade urinveier",
    U85: "Medfødt feil urinveier",
    U88: "Glomerulonefritt/nefropati",
    U90: "Ortostatisk proteinuri",
    U95: "Sten i urinveier",
    U98: "Unormal urinprøve IKA",
    U99: "Urinveissykdom IKA",
    W01: "Spørsmål om svangerskap",
    W02: "Engstelig for svangerskap",
    W03: "Blødning svangerskap",
    W05: "Kvalme/brekninger svangerskap",
    W10: "Prevensjon postkoital antikonsepsjon",
    W11: "Prevensjon p-pille",
    W12: "Prevensjon spiral",
    W13: "Sterilisering (K)",
    W14: "Prevensjon IKA (K)",
    W15: "Infertilitet (K)",
    W17: "Blødning etter fødsel",
    W18: "Postpartum symptomer/plager IKA",
    W19: "Amming symptomer/plager",
    W21: "Bekymret/opptatt av utseende sv skap",
    W27: "Engstelig for komplik sv skap/fødsel",
    W28: "Red funksjonsevne svangerskapsprobl",
    W29: "Sv skap/fødsel sympt/plager IKA",
    W70: "Infeksjon/sepsis barseltid",
    W71: "Infeksjon som kompliser sv skap IKA",
    W72: "Ondartet svulst svangerskap",
    W73: "Godartet/uspes svulst sv skap",
    W75: "Skade som kompliserer svangerskap",
    W76: "Medfødt feil som kompliserer sv skap",
    W78: "Svangerskap bekreftet",
    W781: "Svangerskapskontroll",
    W79: "Uønsket svangerskap",
    W80: "Ekstrauterint svangerskap",
    W81: "Svangerskapsforgiftning",
    W82: "Abort spontan",
    W83: "Abort fremkalt",
    W84: "Svangerskap høyrisiko",
    W85: "Svangerskapsdiabetes",
    W90: "Ukomplisert fødsel levendefødt barn",
    W91: "Ukomplisert fødsel dødfødt barn",
    W92: "Komplisert fødsel levendefødt barn",
    W93: "Komplisert fødsel dødfødt barn",
    W94: "Mastitt i barseltid",
    W95: "Brystsykdom i sv skap/barseltid IKA",
    W96: "Komplikasjoner i barseltid IKA",
    W99: "Svangersk/føds/barsel sykd IKA",
    X01: "Smerte kjønnsorgan (K)",
    X02: "Menstruasjonssmerter",
    X03: "Intermenstruelle smerter",
    X04: "Smerte samleie (K)",
    X05: "Menstruasjon sparsom/sjelden",
    X06: "Menstruasjon kraftig",
    X07: "Menstruasjon uregelmessig/hyppig",
    X08: "Intermenstruell blødning",
    X09: "Premenstruelle symptomer/plager",
    X10: "Forskyvning menstruasjon",
    X11: "Klimakterium symptomer/plager",
    X12: "Postmenopausal blødning",
    X13: "Blødning etter samleie",
    X14: "Utflod fra skjeden",
    X15: "Skjede symptomer/plager IKA",
    X16: "Vulva symptomer/plager",
    X17: "Underliv symptomer/plager (K)",
    X18: "Smerte bryst (K)",
    X19: "Kul i bryst IKA (K)",
    X20: "Brystvorte symptomer/plager (K)",
    X21: "Bryst symptomer/plager IKA (K)",
    X22: "Bekymret/oppt av utseende bryst (K)",
    X23: "Engstelig for kjønnssykdom (K)",
    X24: "Engstelig for seksuell dysfunk (K)",
    X25: "Engstelig for kreft kjønnsorgan (K)",
    X26: "Engstelig for brystkreft (K)",
    X27: "Engstelig sykd kj org/bryst IKA (K)",
    X28: "Red funksjonevne probl kjønnsorg (K)",
    X29: "Kjønnsorgan sympt/plager IKA (K)",
    X70: "Syfilis (K)",
    X71: "Gonokokkinfeksjon (K)",
    X72: "Candidainfeksjon urogenitalt (K)",
    X73: "Trikomonasinfeksjon urogenitalt (K)",
    X74: "Underlivsinfeksjon IKA (K)",
    X75: "Ondartet svulst livmorhals",
    X76: "Ondartet svulst bryst (K)",
    X77: "Ondartet svulst kjønnsorg IKA (K)",
    X78: "Godartet svulst livmor",
    X79: "Godartet svulst bryst (K)",
    X80: "Godartet svulst kjønnsorg IKA (K)",
    X81: "Uspes svulst kjønnsorg IKA (K)",
    X82: "Skade kjønnsorgan (K)",
    X83: "Medfødt feil kjønnsorgan (K)",
    X84: "Vaginitt/vulvitt IKA",
    X85: "Sykdom i livmorhals IKA",
    X86: "Cytologi livmorhals unormal",
    X87: "Fremfall kjønnsorgan (K)",
    X88: "Godartet mammadysplasi",
    X89: "Premenstruelt tensjonssyndrom",
    X90: "Genital herpesvirusinfeksjon (K)",
    X91: "Condylomata acuminata (K)",
    X92: "Klamydiainfeksjon urogenitalt (K)",
    X99: "Kjønnsorgan sykdom IKA (K)",
    Y01: "Smerte penis",
    Y02: "Smerte testikkel/skrotum",
    Y03: "Utflod urinrør/penis",
    Y04: "Penis symptomer/plager IKA",
    Y05: "Skrotum/testikkel sympt/plager IKA",
    Y06: "Prostata symptomer/plager",
    Y07: "Impotens organisk betinget",
    Y08: "Seksuelt problem IKA (M)",
    Y10: "Infertilitet (M)",
    Y13: "Sterilisering (M)",
    Y14: "Prevensjon IKA (M)",
    Y16: "Bryst symptomer/plager (M)",
    Y24: "Engstelig for seksuell dysfunk (M)",
    Y25: "Engstelig for kjønnsykdom (M)",
    Y26: "Engstelig for kreft kjønnsorgan (M)",
    Y27: "Engstelig for sykd kjønnsorg IKA (M)",
    Y28: "Red funksjonsevne prob kjønnsorg (M)",
    Y29: "Kjønnsorgan sympt/plager IKA (M)",
    Y70: "Syfilis (M)",
    Y71: "Gonokokkinfeksjon (M)",
    Y72: "Genital herpesvirusinfeksjon (M)",
    Y73: "Prostatitt/vesikulitt",
    Y74: "Orkitt/epididymitt",
    Y75: "Balanopostitt",
    Y76: "Condylomata acuminata (M)",
    Y77: "Ondartet svulst prostata",
    Y78: "Ondartet svulst kjønnsorg IKA (M)",
    Y79: "Godartet/uspes svulst kjønnsorg (M)",
    Y80: "Skade kjønnsorgan (M)",
    Y81: "Fimose/overflødig forhud",
    Y82: "Hypospadi",
    Y83: "Ikke-descendert testikkel",
    Y84: "Medfødt feil kjønnsorgan IKA (M)",
    Y85: "Prostatahyperplasi",
    Y86: "Hydrocele",
    Y99: "Kjønnsorgan sykdom IKA (M)",
    Z01: "Problem økonomi/fattigdom",
    Z02: "Problem drikkevann/mat",
    Z03: "Problem bolig/nabolag",
    Z04: "Problem sosialt/kulturelt",
    Z05: "Problem arbeidsforhold/yrke",
    Z06: "Problem arbeidsledighet",
    Z07: "Problem utdannelse",
    Z08: "Problem sosial velferd/trygd",
    Z09: "Problem jus/politi",
    Z10: "Problem helsetjen/tilgjengelighet",
    Z11: "Problem det å være syk/compliance",
    Z12: "Problem mellom samlivspartnere",
    Z13: "Problem atferd samlivspartner",
    Z14: "Problem sykdom hos partner",
    Z15: "Problem tap/dødsfall av partner",
    Z16: "Problem med/i forhold til barn",
    Z18: "Problem sykdom hos barn",
    Z19: "Problem tap/dødsfall av barn",
    Z20: "Problem forhold til foreldre/familie",
    Z21: "Problem atferd foreldre/familie",
    Z22: "Problem med sykdom hos foreldre/fam",
    Z23: "Problem tap/dødsfall av foreldre/fam",
    Z24: "Problem med forhold til venner",
    Z25: "Problem vold/traumatisk hendelse",
    Z27: "Engstelig for sosialt problem",
    Z28: "Redusert funksjonsevne sosialt probl",
    Z29: "Sosialt problem IKA",
    tullekode: "Tullekode!"
};
